### ISSUE TITLE
nested route does not load component

### ISSUE THREAD

**Issue by giosifelis** [jorgegorka/svelte-router#99]
Hello,  my nested route does not load the component.  here is my code

` const routes = [ {
    name: 'locations',
    layout: AdminLayout,
    component: LocationsPage,
    onlyIf: { guard: store.isLogged, redirect: '/login' },
    nestedRoutes: [
      {
        name: '/:id',
        component: LocationPage
      }
    ]
  }],`

the LocationPage does not load when i go to locations/1.  The LocationsPage stays loaded.

any idea why?

**Comment by jorgegorka** [comment]
Hi @giosifelis 

What is happening is that named params are always treated as optional so `/locations` and `/locations/123` are resolved by the same component _LocationsPage_ in your case.   The easiest way to solve it is updating this route `name: ':id'`  with something like `name '/show/:id'`  or using singular and plural route names. Here are the two examples:

```:javascript
const routes = [ { name: 'locations', layout: AdminLayout, component: LocationsPage, onlyIf: { guard: store.isLogged, redirect: '/login' }, nestedRoutes: [ { name: '/show/:id', component: LocationPage } ] }],

const routes = [ { name: 'locations', layout: AdminLayout, component: LocationsPage, onlyIf: { guard: store.isLogged, redirect: '/login' },{ name: '/location/:id', layout: AdminLayout, component: LocationPage } ] }],
```

The first example will resolve a route like `/locations/show/123`  and the second one `/location/123`

**Comment by giosifelis** [comment]
I ended up using the second one.  

The first one is still not working.

**Comment by dtzxporter** [comment]
Just ran into this, the first one does not work for whatever reason...

**Comment by dtzxporter** [comment]
finder.js lines 70-71, you can fix the logic there.

**Comment by jorgegorka** [comment]
Hey guys:

This bug has been solved in version 6.0.2

🎉

**Comment by surajsharma** [comment]
> Hey guys:
> 
> This bug has been solved in version 6.0.2
> 
> 🎉

apparently not, could you kindly reopen this issue?

**Comment by Marcel2508** [comment]
Yeah, this seems to be not yet solved..
This example is not working properly (/customer -> Customer component and /customer/123/edit -> Customer component)..
```javascript
  {
        name:"customer",
        component: Customer,
        layout: AppLayout,
        onlyIf: {guard: getPermCheck("customer"), redirect:"/noperm"},
        nestedRoutes:[
            {
                name:"new", //New formular
                component: WIP,
                onlyIf:{onlyIf: getPermCheck("customer_new"),redirect:"/customer"},
                layout: AppLayout,
            },
            {
                name:":id/edit",
                component: CustomerEdit,
                onlyIf:{onlyIf: getPermCheck("customer_edit"),redirect:"/customer2"},
                layout: AppLayout,
            }
        ]
    }
```

Any Idea about this issue?
